### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by LukeAndrewSmith** [shaochuancs/esserializer#101]
I'm trying to import esserializer into a web application I'm working on and run into the above mentioned error when performing:
```import { serialize, deserialize } from 'esserializer';```.
The error occurs in '// ./~/esserializer/dist/bundle.js'.
The same error occurs if I ```const ESSerializer = require('esserializer')```
Please let me know if there's any other info I can provide or if this issue is unrelated to you're code.
Best,
Luke

**Comment by shaochuancs** [comment]
Hi, Luke

Thanks for your feedback. Does this error occur immediately after ESSerializer is required? Or does it occur when performing serialize/deserialize operation? Are you using bundler tool such as webpack or browserify?

Thanks
Chuan

**Comment by LukeAndrewSmith** [comment]
Hi Chuan, 

Thanks for the quick reply, 
The error occurs immediately after requiring. I believe webpack is being used.

**Comment by LukeAndrewSmith** [comment]
Hi Chuan, 
I'm very sorry but I've realised the library is not necessary for my needs (which turned out to be far more simple than I thought) and I'm coding for a private company hence they say they'd rather I recreate the problem in a dummy project rather than share their information, but I also failed to recreate the problem so I'll close the issue for now.
Thanks again for the help,
Best,
Luke

**Comment by shaochuancs** [comment]
That's OK Luke :)

Please let me know once you have any problems on serialization/deserialization.

Chuan
