### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by sidharthv96** [shaochuancs/esserializer#109]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/10703445/200911772-881c328d-4f69-47e9-9773-3db9cde88ccb.png">

<img width="780" alt="image" src="https://user-images.githubusercontent.com/10703445/200911799-3e505679-3f28-4122-9670-1f8c10df4e7d.png">

Seems to be a regression in https://github.com/shaochuancs/esserializer/commit/f22c838ae61f2508f8fd55b2c12361422fc92cd3

Caused failure in https://github.com/mermaid-js/mermaid-live-editor/pull/1077

Logs: https://dashboard.cypress.io/projects/2ckppp/runs/672/test-results/ac70b671-9fa6-4a76-800b-d9d89bbb1757?utm_source=github&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D

**Comment by shaochuancs** [comment]
Thanks @sidharthv96 for your feedback. I'll fix this bug ASAP.

**Comment by shaochuancs** [comment]
Bug fixed in v1.3.5
