### ISSUE TITLE
Doesn't seem to handle getters and setters properly

### ISSUE THREAD

**Issue by sprugman** [shaochuancs/esserializer#3]
This library is so close to doing exactly what I want, but it doesn't appear to work with getters and setters. Perhaps that's because it doesn't create actual class instances, but rather kinda fakes it with some prototype magic?

sample class:

	class Test {
		constructor() {
			console.log('I exist!');
		}

		set name(n) {
			console.log('my setter', n);
			this._name = n;
		}
		get name() {
			console.log('my getter', this._name);
			return this._name;
		}
	}

usage:

	t = new Test()
	> I exist!

	t.name = "Al"
	> my setter Al

	t.name
	> my getter Al

	t instanceof Test
	> true

	str = ESSerializer.serialize(t)
	obj = ESSerializer.deserialize(str, [Test])
	> my getter undefined

	obj.name
	> undefined

	obj._name
	> "Al"
	
	obj instanceof Test
	> false
	
	obj.constructor.name
	> "Test"

**Comment by shaochuancs** [comment]
Thanks @sprugman for your feedback. I've added getter/setter support in the new 1.0.1 version. Please check.

Also, in your example, I find esserializer doesn't handle `instanceof` operator either. I've submitted another issue to track this problem.
